# Generated by Django 5.0.1 on 2024-01-19 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('woodApiV1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ourWork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('image', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('telNumb', models.CharField(max_length=10)),
                ('text', models.CharField(max_length=500)),
                ('time', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='techInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supportTel', models.CharField(max_length=10)),
                ('adress', models.URLField()),
            ],
        ),
        migrations.RemoveField(
            model_name='wood',
            name='something',
        ),
        migrations.AddField(
            model_name='wood',
            name='commonCharacterics',
            field=models.JSONField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='wood',
            name='image',
            field=models.URLField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='wood',
            name='name',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
