# Generated by Django 5.0 on 2024-01-25 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('woodApiV1', '0002_ourwork_question_techinfo_remove_wood_something_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='telNumb',
            field=models.CharField(max_length=13),
        ),
    ]
