# Generated by Django 5.0.1 on 2024-01-28 13:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('woodApiV1', '0005_alter_question_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='selfProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.URLField()),
                ('price', models.IntegerField()),
                ('name', models.CharField(max_length=20)),
                ('wood', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='woodApiV1.wood')),
            ],
        ),
    ]
