# Generated by Django 5.0.1 on 2024-01-30 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('woodApiV1', '0006_selfproduct'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ourWork',
            new_name='ourProduct',
        ),
    ]
