# Generated by Django 5.0.1 on 2024-01-31 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('woodApiV1', '0008_ourproduct_madefrom_delete_selfproduct'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ourproduct',
            name='madeFrom',
        ),
    ]
